// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

console.log(process.env);

const DATABASE_URL =
  process.env.ENV === "production"
    ? process.env.PRODUCTION_DB_URL
    : process.env.DEV_DB_URL;

console.log(DATABASE_URL);
export default defineConfig({
  schema: "server/prisma/schema.prisma",
  migrations: {
    path: "server/prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
