// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/following": {
    params: {};
  };
  "/posts/recent": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/profile/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/posts/following" | "/posts/recent" | "/login" | "/logout" | "/register" | "/profile/:username";
  };
  "routes/posts/posts.jsx": {
    id: "routes/posts/posts";
    page: "/" | "/posts/following" | "/posts/recent";
  };
  "routes/posts/following.jsx": {
    id: "routes/posts/following";
    page: "/posts/following";
  };
  "routes/posts/popular.jsx": {
    id: "routes/posts/popular";
    page: "/";
  };
  "routes/posts/recent.jsx": {
    id: "routes/posts/recent";
    page: "/posts/recent";
  };
  "routes/login/login.jsx": {
    id: "routes/login/login";
    page: "/login";
  };
  "routes/login/logout.jsx": {
    id: "routes/login/logout";
    page: "/logout";
  };
  "routes/register/register.jsx": {
    id: "routes/register/register";
    page: "/register";
  };
  "routes/profile/profile.jsx": {
    id: "routes/profile/profile";
    page: "/profile/:username";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/posts/posts": typeof import("./app/routes/posts/posts.jsx");
  "routes/posts/following": typeof import("./app/routes/posts/following.jsx");
  "routes/posts/popular": typeof import("./app/routes/posts/popular.jsx");
  "routes/posts/recent": typeof import("./app/routes/posts/recent.jsx");
  "routes/login/login": typeof import("./app/routes/login/login.jsx");
  "routes/login/logout": typeof import("./app/routes/login/logout.jsx");
  "routes/register/register": typeof import("./app/routes/register/register.jsx");
  "routes/profile/profile": typeof import("./app/routes/profile/profile.jsx");
};