// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/posts": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/register" | "/posts";
  };
  "routes/home/home.jsx": {
    id: "routes/home/home";
    page: "/";
  };
  "routes/login/login.jsx": {
    id: "routes/login/login";
    page: "/login";
  };
  "routes/login/logout.jsx": {
    id: "routes/login/logout";
    page: "/logout";
  };
  "routes/register/register.jsx": {
    id: "routes/register/register";
    page: "/register";
  };
  "routes/posts/explore.jsx": {
    id: "routes/posts/explore";
    page: "/posts";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home/home": typeof import("./app/routes/home/home.jsx");
  "routes/login/login": typeof import("./app/routes/login/login.jsx");
  "routes/login/logout": typeof import("./app/routes/login/logout.jsx");
  "routes/register/register": typeof import("./app/routes/register/register.jsx");
  "routes/posts/explore": typeof import("./app/routes/posts/explore.jsx");
};